### ISSUE TITLE
[Feature request] Change AsyncBlock->callback to a std::function

### ISSUE THREAD

**Issue by najadojo** [Microsoft/libHttpClient#219]
I'd like to be able to capture values in my lambda:

```
auto asyncBlock = std::make_shared<AsyncBlock>();
asyncBlock->queue = m_HttpQueueHandle;
asyncBlock->callback = [appAuthentication, tce, asyncBlock](AsyncBlock*)
{
    tce.set(appAuthentication);
};
```

**Comment by jasonsandlin** [comment]
We're going for a C API so we can p/invoke.  Feel free to spin up an email with myself and Brian Pepin offline for more detail.  

We've prototyped how to pass std::functions through the callback context as sample code, but haven't flushed it out.
