### ISSUE TITLE
[question] How do I cancel an in progress http call?

### ISSUE THREAD

**Issue by najadojo** [Microsoft/libHttpClient#253]
I have a scenario where we've started a call with HCHttpCallPerformAsync but before the callback has completed we'd like to tear everything down. I've attempted to use HCHttpCallCloseHandle to signal I have no interest in the result but that seems to just cause a crash while the call is processing.

**Comment by jasonsandlin** [comment]
1) Close shouldn't crash but it does.  That's a known bug.  It doesn't yet keep a reference so for now you have to keep the handle open while the async is in flight.  We'll fix this in a upcoming release.

2) The cancel operation isn't hooked up down to the OS APIs (e.g. WinHTTP's cancel, etc) so it won't really cancel yet.  That's work that we'll likely do at some point but isn't yet done.  Its not high on our priority so it'll be done in a future release but if you want to pull request the feature in sooner, feel free :)

**Comment by jasonsandlin** [comment]
Perform now takes a reference so you can Close right away now:
https://github.com/Microsoft/libHttpClient/pull/353
