### ISSUE TITLE
Fix sample or add back "unneeded testweb app"

### ISSUE THREAD

**Issue by namrog84** [Microsoft/libHttpClient#281]
Your http sample uses 
"https://raw.githubusercontent.com/Microsoft/libHttpClient/master/Tests/TestWebApplication/appsettings.Development.json" 
as seen here https://github.com/Microsoft/libHttpClient/blob/master/Samples/Win32-Http/main.cpp#L185

yet in commit #270 you removed the file, so now the sample fails to function because it returns a error code 400.
https://github.com/Microsoft/libHttpClient/commit/1d874050f229d0aa5e4efbb9644141ddf79762e7#diff-90792de52961c34118f976ebe4af3a75

Thanks

**Comment by jasonsandlin** [comment]
Ah, thanks.  We'll get this fixed

**Comment by jasonsandlin** [comment]
Fixed in https://github.com/Microsoft/libHttpClient/pull/282
