### ISSUE TITLE
Fix casing to match. Some compilers are sensitive to capitalization.

### ISSUE THREAD

**Issue by namrog84** [Microsoft/libHttpClient#315]
filename: asyncQueue.h
filename: asyncQueueEx.h

https://github.com/Microsoft/libHttpClient/blob/master/Source/HTTP/httpcall.cpp
#include <AsyncQueueEx.h>

error: non-portable path to file '<asyncQueueEx.h>'; specified path differs in case from file name on disk [-Werror,-Wnonportable-include-path]

Can this casing discrepancy be fixed in a future iteration?

This regression occured in update #307 
commit = c8cb7f79ed8111318e2b78b9d1e31e9a7a3ce92a

**Comment by jasonsandlin** [comment]
Thanks - we'll get this fixed up

**Comment by namrog84** [comment]
Just a follow up with more information. 
The build worked fine for windows.
It broke during our use of Clang v6.0.2 when targeting Android.

I just recently updated our internal clone of libhttpclient because we wanted to disable websockets(because openssl/crypt platform issues), thus why I didn't notice it sooner.

**Comment by rakhad** [comment]
You can find the fix here https://github.com/Microsoft/libHttpClient/pull/316
