### ISSUE TITLE
Double free with mock

### ISSUE THREAD

**Issue by namrog84** [Microsoft/libHttpClient#325]
Since we had written our own thread scheduler to consume the task.  We recently started some seeing unusual results.

I started with a ExampleSingleGenericMock from https://github.com/Microsoft/libHttpClient/blob/master/Tests/UnitTests/Tests/MockTests.cpp

In the same unit test, 
VERIFY_ARE_EQUAL(S_OK, HCHttpCallCloseHandle(call));
HCCleanup();
are both called but inside HCCleanup is where the http_singleton is destroyed

https://github.com/Microsoft/libHttpClient/blob/e7726a89b99b715287469e2651b9b7bff9692797/Source/Global/global.cpp#L45

HCHttpCallCloseHandle(mockCall); is called on all the mock calls.

So HCHttpCallCloseHandle is being called both by the unit test AND in the httpsingleton cleanup.

This caused some unusual behavior.

We ultimately were hitting this assert.   Since it had been free'd earlier, it now contained garbage data (e.g. if (refCount was equal to like -2384234)
  https://github.com/Microsoft/libHttpClient/blob/1d749c20bd522d056f339e18b01d8df70e132482/Source/HTTP/httpcall.cpp#L84

Proposed solutions:
* Remove CallCloseHandle for mocks in the cleanup, and make it behave like non mock, where the user is responsible for cleaning it up.
* Add additional ref counting to the mocks, so that there isn't a double free scenario.

Let me know if you need additional information and clarity.

**Comment by jasonsandlin** [comment]
Feel free to submit a PR to fix it.  Sounds like making it behave like a non-mock is the best choice.

**Comment by namrog84** [comment]
I believe the issue might have been originating from the use of 2 httpcalls in the example. One to setup the fake response and 1 to setup the actual call.
