### ISSUE TITLE
Mock calls internal compare is inadequate, fake race/thread issues

### ISSUE THREAD

**Issue by namrog84** [Microsoft/libHttpClient#326]
We recently ran in our unit tests some unusual behavior that presented as race conditions and other indeterminate behavior.

We built from ExampleSingleGenericMock from https://github.com/Microsoft/libHttpClient/blob/master/Tests/UnitTests/Tests/MockTests.cpp

I had queued up 50+ mock calls into our queue to then be consumed to test our multi threaded worker threads to consume the queue.

The problem presented as if data was being written into different calls. 
The main differentiator in each call was by setting different response bodies. HCHttpCallResponseSetResponseBodyBytes
Essentially setting the response body it as "Mock 1", "Mock 2", "Mock #", etc...

As if were queueing the same endpoint expecting a counter to increase

It was later discovered in
https://github.com/Microsoft/libHttpClient/blob/d0737a7fcb0f563b1dd3cf2cd74977e9dd1efb7d/Source/Mock/mock.cpp#L119

And the eventual call to  https://github.com/Microsoft/libHttpClient/blob/d0737a7fcb0f563b1dd3cf2cd74977e9dd1efb7d/Source/Mock/mock.cpp#L10

That the only differentiator being compared between 2 calls is requestBodyBytes and url.

But there is legitimate reasons why multiple calls should expect different results from the same url. Imagine an endpoint api that just counted how many calls to it, it'd have the same url and request but different results.

Proposed solutions:
* Have a more robust way of identifying comparable mockcalls, by comparing more of the internal call's values.

* Don't maintain an internal m_mocks that you have to match against to begin with, and just let the user feed in the expected call.  I think this is how how traditional non mock calls occur?

**Comment by jasonsandlin** [comment]
The theory is if a matching mock is found it does this logic:

https://github.com/Microsoft/libHttpClient/blob/d0737a7fcb0f563b1dd3cf2cd74977e9dd1efb7d/Source/Mock/mock.cpp#L95

so the first time through it returns the first match mock, and then 2nd time through it uses the 2nd match mock, and the last time+ through it just keeps using the last matching mock.

and you put a break point there and see if its acting right?  There might be a bug in this path

**Comment by namrog84** [comment]
I believe the issue might have been due to a misunderstanding of how the use of 2 HttpCalls occurred in the test. Will re-evaluate and will re-open if something more specific is found.
