### ISSUE TITLE
Proposal/Discussion: Propagate out android exceptions for tracing/debugging. 

### ISSUE THREAD

**Issue by namrog84** [Microsoft/libHttpClient#388]
Java uses typed exceptions which have no error code. 

However because of the c layer here. 
```
HCHttpCallResponseSetNetworkErrorCode(_In_ HCCallHandle call, _In_ HRESULT networkErrorCode, _In_ uint32_t platformNetworkErrorCode)
HCHttpCallResponseGetNetworkErrorCode(_In_ HCCallHandle call, _Out_ HRESULT* networkErrorCode, _Out_ uint32_t* platformNetworkErrorCode)
```
There is nothing to propagate out for platform network error code on android. 

We would like to have more visibility on the other side in c/c++ at least for tracing/debugging. So I was thinking about potential solutions.

I see 2 potential paths. 

Approach 1:  Add 2 new apis
```
HCHttpCallResponseSetNetworkErrorCode(_In_ HCCallHandle call, _In_ HRESULT networkErrorCode, _In_z_ char* platformNetworkErrorStr)
HCHttpCallResponseGetNetworkErrorCode(_In_ HCCallHandle call, _Out_ HRESULT* networkErrorCode, _Out_ char* platformNetworkErrorStr)
```
Alternatively make one with all (call, networkerrorcode, platformnetworkerrorcode, platformnetworkerrorstr)

Approach 2:
Make a java exception : number mapping. So that each exception is mapped to some value. 
For our Java/C++ mapping in our project. We currently use this approach. 

e.g.  
```
ExceptionLookup.put(TIMEOUT.getValue(), TimeoutException.class);
...
static int translateErrorCodeValueFromThrowable(@NonNull Throwable exception) {
```
where TIMEOUT is just a defined value (e.g. TIMEOUT(0x80070102)).  It generally matches the windows based error codes.  Since Android/Java doesn't have any better numbers to choose from aside from maybe some linux ones. 

Either approach I would be willing to implement a rough draft and PR it but before I did any work on it, I was hoping to have some feedback, discussion and thoughts. Just in case the libHttpClient team has given thought to this already.

**Comment by jasonsandlin** [comment]
Approach 1 seems fine to me as the platform network error code is just for debug/tracing and if on the Android side there's no error numbers provided then a string is fine.  Feel free to PR this.   Thanks!

**Comment by jasonsandlin** [comment]
Oh I think to avoid weird client calling patterns that do cross plat this would be even better, so you only get/set the HRESULT networkErrorCode in one API, and its clear what this new thing is for.

HCHttpCallResponseSetNetworkErrorMessage(_In_ HCCallHandle call, _In_z_ char* platformNetworkErrorMessage)
HCHttpCallResponseGetNetworkErrorMessage(_In_ HCCallHandle call, _Out_ char* platformNetworkErrorMessage)

**Comment by jasonsandlin** [comment]
Thanks!
