### ISSUE TITLE
Is it possible to get network failure error code on Android?

### ISSUE THREAD

**Issue by jared-bott** [Microsoft/libHttpClient#398]
When `E_HC_NO_NETWORK` is returned for an Android HTTP request initialization, it seems to be swallowed by the library (when the state is extracted) and calling `XAsyncGetStatus` subsequently returns `0`. We don't want a retry in this situation and would like to be able to act when that error occurs.
Is there a way to get the error code to stay in the `XAsyncBlock`?

**Comment by jasonsandlin** [comment]
Try these APIs:

https://github.com/Microsoft/libHttpClient/blob/master/Include/httpClient/httpClient.h#L506
https://github.com/Microsoft/libHttpClient/blob/master/Include/httpClient/httpClient.h#L519
https://github.com/Microsoft/libHttpClient/blob/master/Include/httpClient/httpClient.h#L493

**Comment by jasonsandlin** [comment]
Ping again if more needed here
