### ISSUE TITLE
Calling SubmitThreadpoolWork when the application is shutting down causes crash

### ISSUE THREAD

**Issue by yazici** [microsoft/libHttpClient#458]
SubmitThreadpoolWork (seems to be an alias for NTDLL.TpPostWork) cannot be called during application shutdown

It throws: Exception thrown at 0x00007FFD726AF220 (ntdll.dll) in CTA_PC.exe: 0xC000000D: An invalid parameter was passed to a service or function. occurred

Our client application that uses this crashes when we close the application using (X) close button on the upper right corner

**Comment by jasonsandlin** [comment]
After discussion, issue is resolved as won't fix
