### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by helenol** [microsoft/libHttpClient#473]
Hi,
Is there any plan to support Linux with this API? It seems odd to offer a multi-platform library and skip probably the easiest platform to implement on.
This is blocking for some projects we are working on, and we were wondering if we have to do this ourselves or if there is already some plan or support.

Thanks a lot!
Helen

**Comment by jasonsandlin** [comment]
No support planned, but it does support Mac and Android so it should be very close.  Feel free to modify it for your needs
