### ISSUE TITLE
Websocket is missing Ping and other functions

### ISSUE THREAD

**Issue by crud-boy** [microsoft/libHttpClient#493]
eg:
   HCWebsocketSendPing
   HCWebsocketSendPong
   HCWebsocketSetTimeout

**Comment by jasonsandlin** [comment]
Ping should be automatically sent out under the covers.  For example:

https://github.com/microsoft/libHttpClient/blob/master/Source/WebSocket/Websocketpp/websocketpp_websocket.cpp#L702
