### ISSUE TITLE
Support big file download or upload?

### ISSUE THREAD

**Issue by zuohouwei** [microsoft/libHttpClient#500]
Hi.
when I use this lib to upload big file to server , it  was always not worked. the reasons as follows:

1.HCHttpCallRequestSetRequestBodyBytes()‘s  param： requestBodyBytes is  in memory. it's easy to cause oom.

2.not support upload progress callback.

Do you plan to support this feature?

Thanks.

**Comment by jasonsandlin** [comment]
No plans as far as I know.  Feel free to add it if you need it

**Comment by zuohouwei** [comment]
I see . 
Thank you.
