### ISSUE TITLE
HCHttpCallResponseSetResponseBodyBytes logs bogus bodySize on Windows x32 debug

### ISSUE THREAD

**Issue by chwarr** [microsoft/libHttpClient#501]
In a Windows x32 (Win32) debug configuration, I'm seeing bogus values for `bodySize` in the [log message written by `HCHttpCallResponseSetResponseBodyBytes`](https://github.com/microsoft/libHttpClient/blob/ce112bfb535fbb68e33ee623556fbf6e6b4040f9/Source/HTTP/httpcall_response.cpp#L91).

Here's an example from some logs that I have handy:

```
HCHttpCallResponseSetStatusCode [ID 1]: statusCode=200
HCHttpCallResponseSetResponseHeader [ID 1]: Cache-Control=no-cache, no-store
...
HCHttpCallResponseSetResponseHeader [ID 1]: Content-Length=1349
HCHttpCallResponseSetResponseBodyBytes [ID 1]: bodySize=9690109650489312581
```

The Content-Length header here is 1349, yet the `bodySize` value logged here is astronomically large.

I don't have a quick way to rebuild libHttpClient inside the program that produced this log, but I was able to overwrite the format string in the debugger to be `...bodySize=%zu`. After that change, I started seeing the values I expected.

The `z` length specifier was added to C++ in C++11. It looks like the minimum C++ supported is C++11, so that could be a fix. If not, casting `bodySize` to a `unsigned long long int` and using `llu` could also work.

I haven't looked to see if this problem exists elsewhere. I've not tested other platforms or configurations either.

**Comment by jasonsandlin** [comment]
Thanks, we'll get this fixed.

**Comment by jasonsandlin** [comment]
Fixed in https://github.com/microsoft/libHttpClient/pull/502.  Thanks!
