### ISSUE TITLE
HTTPS Struggles

### ISSUE THREAD

**Issue by Cry-Luca** [microsoft/libHttpClient#516]
I'd like to point out two limitations in the library I found while trying to deal with self-signed certificates we sometimes use for development purposes.

First of all there seem to be no way to disable SSL peer verification. I totally understand the security implications, but sometimes it's fine to accept "bad" certificates from hosts which we know. Other HTTP libraries I know expose that option (e.g. CURLOPT_SSL_VERIFYPEER), so it only makes sense to me that libHttpClient exposes it as well.

Another related limitation is that the most information the library provides about HTTPS failure (on Windows) is a WINHTTP error code. The one I was always getting is extremely generic (ERROR_WINHTTP_SECURE_FAILURE) and the only way to get more information is to use a WINHTTP_STATUS_CALLBACK. This callback slot is already used by the library and even if I wanted to hook my own callback, I couldn't find a way to retrieve the HINTERNET required to set it up.

**Comment by jasonsandlin** [comment]
Feel free to expose an option to disable SSL verification if you need that and submit a pull request.  

For the error code issue, we can't expose HINTERNET as non-Windows platforms won't know what that is.  But what logic do you want to see in WINHTTP_STATUS_CALLBACK to pull out extra information?  Is it just for debugging or does your code need to handle different types of HTTPS failures differently?

**Comment by Cry-Luca** [comment]
Sure, I wouldn't have any problem adding it myself. Do you have suggestions about how this option  should be named and where it should be placed?

Regarding the status callback, it would be enough for me to have some tracing logs to make debugging easier.

**Comment by jasonsandlin** [comment]
For the option, I would expose it per http call handle, you can expose it similar to HCHttpCallSetTracing.  
https://github.com/microsoft/libHttpClient/blob/master/Include/httpClient/httpClient.h#L280
You'll see how that sets a bool.  Call it something like HCHttpCallSetSSLValidation and default to true and doc in the summary that calling it is optional to turn off ssl validation.

Feel free to add logging lines to that callback and send a PR request.  
Here's an example:

   HC_TRACE_ERROR(HTTPCLIENT, "HCHttpCallPerform [ID %llu]: failed", TO_ULL(static_cast<HC_CALL*>(call)->id)); }

Then in your game, use
https://github.com/microsoft/libHttpClient/blob/master/Include/httpClient/trace.h#L152
to set the trace level, and use
https://github.com/microsoft/libHttpClient/blob/master/Include/httpClient/trace.h#L189
or
https://github.com/microsoft/libHttpClient/blob/master/Include/httpClient/trace.h#L182
to set a callback which gets the trace

**Comment by Cry-Luca** [comment]
Considering WINHTTP_OPTION_SECURITY_FLAGS can only be set on the handle returned by WinHttpOpenRequest(), I think **Request** should be part of the name? That is, HCHttpCallRequestSetSSLValidation() instead of simply HCHttpCallSetSSLValidation()?

Even though I'm not really familiar with the platform, I also gave a quick look at the Android implementation, but it doesn't seem as easy. Okhttp seems to be providing this kind of toggle as part of the overarching client interface, and not on a per request basis (https://stackoverflow.com/questions/25509296/trusting-all-certificates-with-okhttp).

**Comment by jasonsandlin** [comment]
Ya HCHttpCallRequestSetSSLValidation is fine and matches the other request setters.  Its fine to doc that this only works on Windows for now.  Others can hook it up on other platforms as they need it.  I mainly want to keep the api cross plat even if it some knobs don't apply on some platforms yet.

**Comment by jasonsandlin** [comment]
Thanks!  You'll need to do that CLA in the PR to confirm it doesn't have IP and so on or we can't take it.

**Comment by jasonsandlin** [comment]
Merged.  Thanks again Luca!
