### ISSUE TITLE
RootTrustManager not found on Kindle Fire devices

### ISSUE THREAD

**Issue by v-davwes** [microsoft/libHttpClient#534]
Changes introduced with #461 don't work on Kindle Fire devices. `android/security/net/config/RootTrustManager` is not found causing cert chain verification to fail. The code works as expected on non amazon devices. A similar [issue](https://github.com/microsoft/cpprestsdk/issues/1313) in cpprestsdk has an alternate solution that may work for Kindle devices as well but I haven't tested it

**Comment by jasonsandlin** [comment]
Feel free to PR fix, or talk to us on private channels to coordinate plan.
