### ISSUE TITLE
Large file support

### ISSUE THREAD

**Issue by stephenwhittle** [microsoft/libHttpClient#537]
I understand from https://github.com/microsoft/libHttpClient/issues/500 that you won't be providing an official implementation for this, but it's a requirement for my current project.
If we go ahead and implement that functionality, would you consider a PR that does so for Windows/GDK only? Android/Apple etc are out of scope for us.

**Comment by jasonsandlin** [comment]
Yes, as long as it doesn't cause trouble with that sounds good.

Also be aware you'll need to sign to the Microsoft CLA: https://cla.opensource.microsoft.com/ as per Microsoft policy.  The github bot will guide you through the process when you submit a PR.

**Comment by jamesford42** [comment]
By "large file" how big do you mean? I was planning to use libhttpclient for POST with a body up at around 10 mb. Is that going to be a problem?

**Comment by stephenwhittle** [comment]
If you've got 10MB of memory spare, no :)

At the moment the current WinHTTP implementation grows its internal buffer to store the entire response (ie it resizes, then appends to the end of the buffer on `WINHTTP_CALLBACK_STATUS_DATA_AVAILABLE`), so the issue is more about running out of memory if you, for instance, make a GET request for a file that's a couple hundred MB+.

**Comment by jasonsandlin** [comment]
Closing this out but feel free to open a PR if you want the support as discussed.
