### ISSUE TITLE
Be able to query if library has been initialized

### ISSUE THREAD

**Issue by jafristr** [microsoft/libHttpClient#655]
We have a bit of a maze of dependencies and devices and builds that initialize libhttpclient differently - some do it through xsapi, some do it through the gamecore GDK, some include libhttpclient separately and initialize it there - on Android it's called asynchronously from the java thread and we need to synchronize on that - if we have to track it ourselves, there are a handful of places where we'd have to flip a "we've called HCInitialize or something that calls it" bool and it would be easy to miss one. 
Ideally we'd have readonly access to s_useCount from https://github.com/microsoft/libHttpClient/blob/1d7b29a29a20fd6bb7adf3148f039ec102f96cc9/Source/Global/global.cpp#L35 - but maybe there's something else I'm not seeing that we could use. (I haven't looked that hard, to be honest.)

**Comment by jplafonta** [comment]
If a component relies on libHttpClient, it should call HCInitialize upon startup and HCCleanup (or preferably HCCleanupAsync) when it is no longer needed.  This is how XSAPI initializes LHC; games should be able to do the same without any issues.  The one caveat is that if HCCleanup returns E_HC_INTERNAL_STILLINUSE it isn't necessarily indicative of an error.

Is there a specific scenario you have in mind where having access to the use count would be helpful?  Each component should be able to Initialize/Cleanup LHC independently without knowledge of other components.

**Comment by jasonsandlin** [comment]
Got it.  PR out to add this one
