### ISSUE TITLE
Provide an example how to shutdown websockets safely

### ISSUE THREAD

**Issue by redbaron** [microsoft/libHttpClient#678]
Callbacks passed to `HCWebsocketCreate` are executed on unspecified threads, which creates a problem for clean shutdown when libhttpclient is used within user object instances and therefore can't use global singletons.

 Take this websocket example from Microsoft:

1. `this` is passed as context in `HCWebsocketCreate`'s callbacks:

https://github.com/microsoft/Xbox-GDK-Samples/blob/67f3650ebb5ec10e49b74cf3537ad1cdf75a5f30/Samples/Live/SimpleWebSockets/SimpleWebSockets/SimpleWebSockets.cpp#L538

2. `websocket_close` callback casts pointer to the `Sample *` and accesses  it:

https://github.com/microsoft/Xbox-GDK-Samples/blob/67f3650ebb5ec10e49b74cf3537ad1cdf75a5f30/Samples/Live/SimpleWebSockets/SimpleWebSockets/SimpleWebSockets.cpp#L538

https://github.com/microsoft/Xbox-GDK-Samples/blob/67f3650ebb5ec10e49b74cf3537ad1cdf75a5f30/Samples/Live/SimpleWebSockets/SimpleWebSockets/SimpleWebSockets.cpp#L853-L858

3. In destructor `HCWebsocketDisconnect` is called: 

https://github.com/microsoft/Xbox-GDK-Samples/blob/67f3650ebb5ec10e49b74cf3537ad1cdf75a5f30/Samples/Live/SimpleWebSockets/SimpleWebSockets/SimpleWebSockets.cpp#L518-L530

What I observe in my code is that destructor completes and frees `this`, then `websocket_close` is called and tries to access already freed object.  

It looks like with manual Completion port dispatch it is possible  to pump queue in destructor , delaying object destruction until `websocket_close` finishes and for other dispatch modes wait on conditional var might be an option.

It would be nice if libhttpclient repo provided complete example, showing safe use of libhttpclient without global variables.

**Comment by jplafonta** [comment]
Thanks for the feedback.  Your analysis is correct.  Another option is to leverage smart pointers in the callback context, which is what we do internally.  I will open a task on our side to update the sample to demonstrate and I'll leave this issue open until then.
