### ISSUE TITLE
Is this library support Hololens2?

### ISSUE THREAD

**Issue by songguanqing** [microsoft/libHttpClient#712]
Is this library support Hololens2?

**Comment by jasonsandlin** [comment]
No work has been done in that direction, but it is cross platform and you're welcome to mess with it if its useful.

**Comment by songguanqing** [comment]
A new doubt.
"libHttpClient.142.UWP.C" is used to generate the Lib library.
And "Http2019" is a sample.
But how does "Http2019.exe" call that library?
I don't see any project settings that can link this static library to the example.
This makes me very confused

**Comment by jasonsandlin** [comment]
It includes a props files to setup the link.  See:

https://github.com/microsoft/libHttpClient/blob/main/Samples/UWP-Http/Http.vcxproj#L104

To add the props file to your project by clicking "View->Other Windows->Property Manager", right clicking on your project, selecting "Add Existing Property Sheet", then finally selecting the props file.

**Comment by songguanqing** [comment]
But in the props files,I don't see a library named "libHttpClient.142.UWP.C.lib"

**Comment by jasonsandlin** [comment]
include & build this vcxproj 
https://github.com/microsoft/libHttpClient/tree/main/Build/libHttpClient.141.UWP.C 
and you'll see it.

If you open the sln at the root, eg for VS2017 use https://github.com/microsoft/libHttpClient/blob/main/libHttpClient.vs2017.sln
and you'll see the various vcxprojs included.

**Comment by songguanqing** [comment]
OK,Thanks a lot.
For example, the following specific interface: HCHttpCallRequestSetUrl
It declared in httpclient.h.
When I run the example program "Http2019",what really makes this interface work?
LibHttpClient.142.UWP.C.lib or source file？

**Comment by jasonsandlin** [comment]
the api of httpclient.h is inside LibHttpClient.142.UWP.C.lib.  
to use, link to the static lib you've previously built

**Comment by songguanqing** [comment]
Thank you so much.
