### ISSUE TITLE
networkErrorCode limitations

### ISSUE THREAD

**Issue by kuznetsoveugene** [microsoft/libHttpClient#734]
From the documentation of the `HCHttpCallResponseGetNetworkErrorCode`
`// <param name="networkErrorCode">The network error code of the HTTP call. Possible values are S_OK, or E_FAIL.</param>`

It is being claimed that possible return values are OK or ERROR but in reality, other states may come out such as `E_HC_NO_NETWORK`. Is that an error in the documentation? 

Why does `networkErrorCode` is so limited in possible return values? It is losing its purpose if you cannot fetch a meaningful cross-platform error out of it and will have to derive the error from `platformNetworkErrorCode`. 

Looking for more information and usages about this feature.

**Comment by kuznetsoveugene** [comment]
Ping for update, it has been a month

**Comment by jasonsandlin** [comment]
What would you like to see beyond E_HC_NO_NETWORK?   In our usage of LHC we don't do anything differently based on the type of network failure as we just treat all network failures the same.  For debugging, we log platformNetworkErrorCode to track down real cause but don't take different logical actions based on it.
