### ISSUE TITLE
Add option to use cpprest or json for moddern c++ (json.hpp)

### ISSUE THREAD

**Issue by AraHaan** [Microsoft/libHttpClient#76]
I have a version of the nlohmann json for moddern C++, it would be nice if there really is a way to use that instead of cpprest's json implementation.

If possible prvide steps please (I perfer that json implementation for now that I already have as I do not have issues with it yet).

**Comment by jasonsandlin** [comment]
You can use anything you like.  Like the readme at https://github.com/Microsoft/libHttpClient/tree/master/Include/json_cpp says, its there for games that don't have a JSON parser that don't want to take a full dependancy on cpprest, but if you have a better JSON parser go for it.  libhttpclient itself doesn't do JSON parsing.  Its just provided as an extra side header.

**Comment by AraHaan** [comment]
Ah, ok I see thanks.
